# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: continuos_integration
  steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'run app'

  - script: |
      npm run test:coverage
    displayName: 'run test coverage'

  - script: |
      coverage=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
      min_coverage=70
      if (( $(echo "$coverage < $min_coverage" | bc -l) )); then
        echo "O coverage de testes é $coverage e é inferior a $min_coverage%. Abortando o pull request."
        exit 1
      fi
    displayName: 'validate test coverage'